export const carreer = [
  {
    title: 'Senior Software Engineer',
    company: 'Gojob',
    date: '09/2021 - Présent',
    location: 'Aix-en-Provence (13)',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    tags: ['Mongo', 'Express', 'React', 'Node'],
    logo: 'https://pbs.twimg.com/profile_images/1050443488750432256/PN_I5W26_400x400.jpg',
    color: 'rgb(33, 150, 243)',
    id: 0,
  },
  {
    title: 'FullStack Software Engineer',
    company: 'Gojob',
    date: '05/2020 - 08/2021',
    location: 'Aix-en-Provence (13)',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    tags: ['Mongo', 'Express', 'React', 'Node'],
    logo: 'https://lh3.googleusercontent.com/8x9kLvr96DIpUqMgTUA49KjODTlJYA6kHcsPyB6tasNn3pKoxrUlMFtLhl1Q8kPyADRsX8J0nvNjF3UjIw0',
    color: 'rgb(33, 150, 0)',
    id: 1,
  },
  {
    title: 'R&D Engineer',
    company: 'Thales Services SAS',
    date: '08/2015 - 04/2020',
    location: 'Sophia Antipolis (06)/ Aix-en-Provence (13)',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
    logo: 'https://philosophiedelasmartcity.fr/wp-content/uploads/2020/06/logo-thales.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    color: 'rgb(255, 150, 243)',
    id: 2,
  },
];